site:
  title: Open Liberty Docs
  start_page: ROOT::overview.adoc
content:
  sources:
  - url: https://github.com/OpenLiberty/docs.git
    branches: [v23.0.0.12, v24.0.0.3, v24.0.0.6, v24.0.0.9, v24.0.0.12, v25.0.0.3, v25.0.0.6, v25.0.0.7, v25.0.0.8, v25.0.0.9, v25.0.0.10, v25.0.0.11]
  - url: https://github.com/OpenLiberty/docs-generated.git
    branches: [v23.0.0.12, v24.0.0.3, v24.0.0.6, v24.0.0.9, v24.0.0.12, v25.0.0.3, v25.0.0.6, v25.0.0.7, v25.0.0.8, v25.0.0.9, v25.0.0.10, v25.0.0.11]
urls:
  latest_version_segment: latest
antora:
  extensions:
    - scripts/custom-sort.js
asciidoc:
  attributes:
    icons: font
    source-highlighter: highlightjs
    allow-uri-read: true
  extensions:
    - scripts/ol-asciidoc.js
ui:
  bundle:
    url: src/main/content/antora_ui/build/ui-bundle.zip
    snapshot: true
  default_layout: general-reference
