--- 
asciidoc: 
  attributes: 
    allow-uri-read: true
    icons: font
    source-highlighter: highlightjs
  extensions: 
    - ../../../../scripts/ol-asciidoc.js
content: 
  sources: 
    - 
      branches: 
        - v*.0.0.*-staging
        - staging
        - "!v20.0.0.7"
      url: "https://github.com/OpenLiberty/docs.git"
    - 
      branches: 
        - v*.0.0.*-staging
        - staging
        - "!v20.0.0.7"
      url: "https://github.com/OpenLiberty/docs-generated.git"
site: 
  start_page: "ROOT::overview.adoc"
  title: "Open Liberty Docs"
ui: 
  bundle: 
    snapshot: true
    url: src/main/content/antora_ui/build/ui-bundle.zip
  default_layout: general-reference
