site:
  title: Open Liberty Docs
  start_page: ROOT::overview.adoc
content:
  sources:
  - url: https://github.com/OpenLiberty/docs.git
    branches: [v22.0.0.6]
  - url: https://github.com/OpenLiberty/docs-generated.git
    branches: [v22.0.0.6] 
urls:
  latest_version_segment: latest
antora:
  extensions:
    - scripts/custom-sort.js
asciidoc:
  attributes:
    icons: font
    source-highlighter: highlightjs
    allow-uri-read: true
    language: es
  extensions:
    - scripts/ol-asciidoc.js
output:
  clean: true
  dir: ./es
ui:
  bundle:
    url: src/main/content/antora_ui/build/ui-bundle.zip
    snapshot: true
  default_layout: general-reference

  

